### ISSUE TITLE
 密码信息

### ISSUE THREAD

**Issue by AhsanRafiqHussain** [KEN-LJQ/WMS#10]
请授予admin的密码。

我无法登录
谢谢

**Comment by KEN-LJQ** [comment]
你好网页上预填充的就是1001账号就是admin，密码是：123456

**Comment by liu353066462** [comment]
有没有开发文档帮主学习者理解这个项目

**Comment by liu353066462** [comment]
可以加你的QQ吗

**Comment by KEN-LJQ** [comment]
可以的，我的QQ：1120799726

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by AhsanRafiqHussain** [comment]
感谢ken，我用你的项目进行学习。这是非常好的项目，安全，框架和实施。 请仔细更新像我这样的学生的主要渠道，因为我不明白中文，并使用Google Translater进行协调和理解。 最好的祝福阿桑・拉菲克巴基斯坦


________________________________
