### ISSUE TITLE
AccountSessionListener 没有记录用户退出时的日志

### ISSUE THREAD

**Issue by 37305562** [KEN-LJQ/WMS#11]
AccountSessionListener 的sessionDestroyed方法在用户退出时没有调用，大家遇到这个问题了吗，还是我的环境有问题。

**Comment by KEN-LJQ** [comment]
你好，我刚刚看了一下的确出现了这个问题。我会尽快查明原因并修复，如果你找到了原因也欢迎反馈或提交PR。

**Comment by KEN-LJQ** [comment]
你好，问题已经找出来了，原因是：我在实现在线人数控制功能时，定义了`SessionManager`的实现是`DefaultWebSessionManager`，则覆盖掉了原来`DefaultWebSecurityManager`的默认SessionManager实现`ServletContainerSessionManager`，这两个实现的区别是：`ServletContainerSessionManager`使用的servlet容器提供的会话管理，而`DefaultWebSessionManager`使用的是Shiro自己维护的会话管理。这就导致了原来的基于Servlet容器实现的SessionListener失效。
问题的解决办法是：继承Shiro的`SessionListenerAdapter`来实现Session的事件监听
