### ISSUE TITLE
直接用maven编译后复制目录到tomcat中，tomcat manager显示在运行但访问localhost/WMS显示404

### ISSUE THREAD

**Issue by userjia** [KEN-LJQ/WMS#13]

**Comment by userjia** [comment]
ejconnect 部分有一个entity说namespace找不到，会不会是这个bug没解决？但是一开始的主页显示应该和这个没关系吧。我用eclipse导入的项目，tomcat7,8都说不支持，改用9。不知道大家有没有遇到过这样的问题，求大神指点啊

**Comment by KEN-LJQ** [comment]
你好，项目不能被访问可能是端口问题，可以检查一下。另外我开发使用的是tomcat7，故后续版本应该是对其没有影响的

**Comment by userjia** [comment]
感谢，我再试试

**Comment by userjia** [comment]
重头搞了一下，它这样T_T
[INFO] tomcatManager status code:200, ReasonPhrase:OK
[INFO] FAIL - Deployed application at context path /WMS but context failed to start

**Comment by KEN-LJQ** [comment]
如果启动过程中控制台或日志中有报错的话，请把详细的错误贴出来，不然很难定位错误的地方

**Comment by userjia** [comment]
搞出来了，是我数据库没开，非常感谢
