### ISSUE TITLE
登录按钮的url问题

### ISSUE THREAD

**Issue by Bbbzhao** [KEN-LJQ/WMS#2]
在登录界面，输入正确的帐号，密码与验证码，点击登录按钮，**会直接跳404界面**。
通过查阅login.jsp代码后，我修改了这段代码

//修改前
`window.location.href = "/WMS";`
//修改后
`window.location.href = "/mainPage";`

并且在PageForwardHandler这个controller中添加对 /mainPage的处理
 `@RequestMapping("mainPage")`
    `public String showLoginView() {`
        `Subject currentSubject = SecurityUtils.getSubject();`
       ` if (!currentSubject.isAuthenticated())`
           ` return "login";`
       ` else`
          `  return "mainPage";`
    `}`

于是问题来了！
作者是能够成功部署到个人网站http://www.ken-ljq.xyz:8080/WMS
那这是一个Bug？
还是我idea环境有问题？
希望得到作者指点！

**Comment by KEN-LJQ** [comment]
麻烦给出跳404界面时对应的URL

**Comment by Bbbzhao** [comment]
![snip_20170411192309](https://cloud.githubusercontent.com/assets/20168428/24906977/c4830334-1eec-11e7-8716-2fe720bb18b3.png)

**Comment by KEN-LJQ** [comment]
根据你说的可以进入登陆界面，在提交登陆信息后出现404 error， 而且从截图来看像是登陆成功后重定向出现问题了。试一下改为`window.location.href = "/WMS/";`吧，因为我发现在浏览器运行的时候出现一个302响应，而你这里没有
![default](https://cloud.githubusercontent.com/assets/16650282/24914037/9a282eca-1f05-11e7-8d6e-fe94a0d86bca.PNG)

**Comment by Bbbzhao** [comment]
修改成`window.location.href = "/WMS/";`也是不能正常访问...
我可以正常访问您部署的网站。
顺便提一下，新增管理员功能失效。
因为木有id值，生成密码的时候会炸

**Comment by KEN-LJQ** [comment]
感谢，新增管理员功能的确失效了，不过现在已经修复好了。

**Comment by Bbbzhao** [comment]
请问您是否修改了tomcat中的设置？
能否贴出您idea中tomcat的配置，我是初学者，可能有些基本的设置我没有做 TvT
或者您换一台电脑部署项目，会不会出现登陆报404的情况。
在3月9号提交的项目我还可以通过更改登陆登陆按钮的url实现登陆，
新提交的项目不能通过这个方法登陆了....
登陆后报404错误，我点击浏览器后退，再点击刷新，想通过session进入mainPage，报500错误

**Comment by KEN-LJQ** [comment]
回答以下你的问题吧
1. 我在本机的Tomcat配置和服务器上的Tomcat配置都是默认的，没作修改
2. 我使用的是 IDEA Community 版本，不带Tomcat，所以我使用的是Maven的Tomcat插件，我在`pom.xml`文件中配置的这个插件。不知道你是不是使用 Ultimate 版本并且使用内置的Tomcat工具（这里有可能是问题的原因）
3. 我新提交的版本在本机和服务器上都可以正常运行和访问，使用Chrome和IE测试过都可以
4. 你提到的想通过session登陆，然后报500错误，麻烦将显示抛出的异常或者记录到Tomcat`webapps/WMS/WEB-INF/logs`路径下的'applicationException'文件中对应的异常贴出来，并且检查以下数据库的'wms_access_record'表有没有登入记录

**Comment by Bbbzhao** [comment]
<ul>
<li>我注释了pom中的tomcat插件，登陆后报404的问题依然存在，现在是修改controller实现正常登陆。</li>
<li>session登陆报500的错误是我个人原因，实在不好意思TvT</li>
<li>能在作者的项目中学习到很多新知识，十分感谢！</li>
</ul>

**Comment by Bbbzhao** [comment]
#21 解决
