### ISSUE TITLE
（新手）在IDEA部署好了，登陆了直接报404，请问如何解决？

### ISSUE THREAD

**Issue by Magicicon** [KEN-LJQ/WMS#22]
账号填的1001，密码乱写的123456，登陆进去直接报404，请问如何解决？（密码可以说下嘛）

**Comment by KEN-LJQ** [comment]
账号1001，原始密码123456，这个是没有问题的。至于页面跳转报404可能跟你的 Tomcat 配置有关，你可以看看是不是跟 #21 一样都是http://localhost:8080 就可以正常访问，然后尝试搜索并自行处理一下。

**Comment by KEN-LJQ** [comment]
另外一点就是，这个项目是我当时学习 Java Web 时的练手项目，现在已不再维护。但是希望这个项目能够给到各位正在学习 Java 后端开发的童鞋一点小小的帮助，敬请原谅。

**Comment by Magicicon** [comment]
emmmm我的端口是1010
输入好账号密码验证码点击登录就报404了
![0g14_orfnki 53 qxhgd d9](https://user-images.githubusercontent.com/27053753/34656196-288ae3a8-f451-11e7-83c0-121d135da9ee.png)
![w ehpeu4 n 5 06w6a6ds l](https://user-images.githubusercontent.com/27053753/34656197-28c2cb6a-f451-11e7-98e6-f56648392845.png)
