### ISSUE TITLE
大牛，想用你做项目学习。

### ISSUE THREAD

**Issue by Tulaoban** [KEN-LJQ/WMS#4]
部署好后发现所有的列表功能好像没实现。还是我没弄好的原因。新手望知道

**Comment by KEN-LJQ** [comment]
麻烦明确指明列表功能指的是什么。项目中已经实现的功能示范可以参照我的部署[WMS](http://www.ken-ljq.xyz:8080/WMS)。

**Comment by Tulaoban** [comment]
我的指的是各个对象数据的列表，比如仓库在数据中有，但是页面没有数据库的数据。
