### ISSUE TITLE
时间控件的endDate问题

### ISSUE THREAD

**Issue by Bbbzhao** [KEN-LJQ/WMS#5]
<ul>
<li><strong>问题描述</strong></li>
选取含有时间控件的页面，选择任一开始时间，选择<strong>今天</strong>为结束时间，点击查询，不能查询到<strong>今天</strong>的记录。

<li><strong>问题原因</strong></li>
在前端页面，取得结束时间为2017-04-19，并且将值传给service层处理，`endDate = dateFormat.parse(endDateStr);`，此时endDate为Wed Apr 19 <strong>00:00:00</strong> CST 2017，因为时分秒都为0，在sql中就查不出2017-04-19的数据。

<li><strong>个人解决方法</strong></li>
对endDate进行时间的增加，`newEndDate = new Date(endDate.getTime()+(24*60*60*1000)-1);`，使newEndDate为Wed Apr 19 <strong>23:59:59</strong> CST 2017
</ul>
<br />
<br />
想请问作者，是否由更好的解决办法呢，单纯的增加时间，可读性很差

**Comment by KEN-LJQ** [comment]
这个问题我知道了，很感谢你的参与和提出解决办法

**Comment by Bbbzhao** [comment]
感谢，学习了！
