### ISSUE TITLE
导入sql出错

### ISSUE THREAD

**Issue by wym3253** [KEN-LJQ/WMS#7]
使用workbench导入sql文件提示：
INSERT INTO `wms_user` VALUES (1001,'admin','6f5379e73c1a9eac6163ab8eaec7e41c'),(1018,'王皓','50f202f4862360e55635b0a9616ded13'),(1019,'李富荣','c4b3af5a5ab3e3d5aac4c5a5436201b8')
Error Code: 1136. Column count doesn't match value count at row 1

**Comment by KEN-LJQ** [comment]
上述问题出现的原因是：`createtable.sql`文件中第188行的系统用户信息SQL导入语句错误，缺少一列的值，修改后为：`INSERT INTO `wms_user` VALUES (1001,'admin','6f5379e73c1a9eac6163ab8eaec7e41c',0),(1018,'王皓','50f202f4862360e55635b0a9616ded13',1),(1019,'李富荣','c4b3af5a5ab3e3d5aac4c5a5436201b8',1);`。另外项目更改已经提交。
